
# install wireguard on Ubuntu
- name: install wireguard on Ubuntu
  apt:
    name: wireguard
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - wireguard


# Deploy server configuration if server is true 
- name: Deploy wireguard configuration
  template:
    src: wireguard-server.conf.j2
    dest: /etc/wireguard/wg0.conf
  when: wireguard_server == true
  notify: restart wireguard
  tags:
    - wireguard 

