---
# handlers file for ansible-role-wireguard

- name: reload firewalld
  service:
    name: firewalld
    state: restarted

- name: restart wireguard
  service:
    name: wg-quick@wg0
    state: restarted